version: '3'
services:

  tenable-ui:
    build: ./tenable
    ports:
      - "5000:5000"
    volumes:
      - ./tenable:/app

  data-api:
    build: ./data-api
    ports:
      - "5001:5001"
    volumes:
      - ./data-api:/app

  session-api:
    build: ./session-api
    ports:
      - "5002:5002" 
    volumes:
      - ./session-api:/app

  db-load:
    build: ./db-load
    depends_on:
      - stats-db
    env_file:
      - ./db-load/.env

  stats-db:
    image: postgres:latest
    container_name: stats-db
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_password
    ports:
      - "5432:5432" 
    volumes:
      - ./stats-db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  session-db:
    image: postgres:latest
    container_name: session-db
    environment:
      POSTGRES_DB: session_db
      POSTGRES_USER: session_user
      POSTGRES_PASSWORD: session_password
    ports:
      - "5433:5432"
    volumes:
      - ./session-db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  utilities:
    build: ./utilities
    volumes:
      - ./utilities:/app
    env_file:
      - ./utilities/.env
    